name: CD Pipeline

on:
  push:
    branches: [dev, main]

env:
  PROJECT_ID: gacs-playground
  GAR_LOCATION: us-central1
  REPOSITORY: container-images
  SERVICE: ${{ github.ref_name == 'main' && 'github-actions-prod' || 'github-actions' }}
  REGION: us-central1
  WIP: projects/130218930734/locations/global/workloadIdentityPools/github-actions-pool-2/providers/github-actions-provider-3
  SA: github-actions-2@gacs-playground.iam.gserviceaccount.com

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: GCP auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        create_credentials_file: true
        workload_identity_provider: ${{ env.WIP }}
        service_account: ${{ env.SA}}

    - name: Docker auth
      id: docker-auth
      uses: docker/login-action@v3
      with:
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: Build container
      run: docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./

    - name: Push container
      run: docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

  approval:
    needs: build

    environment: dev

    runs-on: ubuntu-latest

    steps:
      - name: Approved
        run: echo Approved
            
  deploy:
    needs: approval

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIP }}
          service_account: ${{ env.SA}}

      - name: GCP Cloud Run deploy
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          flags: --allow-unauthenticated
          project_id: ${{ env.PROJECT_ID }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          # NOTE: You can also set env variables here:
          #  env_vars: |
          #  NODE_ENV=production
          #  TOKEN_EXPIRE=6400

      - name: Show URL
        run: echo ${{ steps.deploy.outputs.url }}